env:
  browser: true
  es2020: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: 0,
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }],
  react/jsx-props-no-spreading: 0
}
