export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";

export const SET_SELECTION = "SET_SELECTION";
export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";
